export const FETCH_OFFICES_DATA = "FETCH_OFFICES_DATA"
export const FETCH_OFFICES_FAILED = "FETCH_OFFICES_FAILED"
export const FETCH_OFFICES_SUCCESS = "FETCH_OFFICES_SUCCESS"

export const FETCH_OFFICES_DETAIL = "FETCH_OFFICES_DETAIL"
export const FETCH_OFFICES_DETAIL_FAILED = "FETCH_OFFICES_DETAIL_FAILED"
export const FETCH_OFFICES_DETAIL_SUCCESS = "FETCH_OFFICES_DETAIL_SUCCESS"

export const SET_OFFICES_PAGE = "SET_OFFICES_PAGE"
export const SET_OFFICES_PAGE_SIZE = "SET_OFFICES_PAGE_SIZE"